version: '3.7'

services:
  aws:
    image: localstack/localstack
    ports:
      - '48612:4566'
    environment:
      SERVICES: s3
    volumes:
      - aws-data:/var/lib/localstack/data
  
  keycloakdb:
    image: postgres
    ports:
      - '56111:5432'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloakdb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - '56221:8080'
    depends_on:
      - keycloakdb

  peaklimsdb:
    image: postgres
    restart: always
    ports:
      - '38869:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_peaklims
    volumes:
      - peaklimsdb-data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
#    port mappings: https://www.jaegertracing.io/docs/1.32/getting-started/
    ports:
      - "58158:5775/udp"
      - "58157:6831/udp"
      - "58159:6832/udp"
      - "58160:5778"
      - "58161:16686"
      - "58162:14250"
      - "58163:14268"
      - "58164:14269"
      - "58165:9411"

        
volumes:
  # compose volumes marker - do not delete
  keycloak-data:
  peaklimsdb-data:
  aws-data:
