version: '3.7'

services:
  aws:
    image: localstack/localstack
    ports:
      - '48612:4566'
    environment:
      SERVICES: s3
    volumes:
      - aws-data:/var/lib/localstack/data
  
  keycloakdb:
    image: postgres
    ports:
      - '56111:5432'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-data:/var/lib/postgresql/data
  
  keycloak:
    image: sleighzy/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloakdb
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_HTTP_PORT: 8080
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, 
      # and it shouldn't be used in production without knowledge. It is highly recommended that you read the 
      # PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 56221:8080
    depends_on:
      - keycloakdb

  peaklimsdb:
    image: postgres
    restart: always
    ports:
      - '38869:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_peaklims
    volumes:
      - peaklimsdb-data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
#    port mappings: https://www.jaegertracing.io/docs/1.32/getting-started/
    ports:
      - "58158:5775/udp"
      - "58157:6831/udp"
      - "58159:6832/udp"
      - "58160:5778"
      - "58161:16686"
      - "58162:14250"
      - "58163:14268"
      - "58164:14269"
      - "58165:9411"

        
volumes:
  # compose volumes marker - do not delete
  keycloak-data:
  peaklimsdb-data:
  aws-data:
